# Generated by Django 3.2.16 on 2022-12-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='gggg', height_field='100px', upload_to='gallery', width_field='100px'),
            preserve_default=False,
        ),
    ]
