# Generated by Django 3.2.16 on 2022-12-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_rename_img_movie_imag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imag',
            field=models.ImageField(upload_to='gal'),
        ),
    ]
